[
  {
  "info": {},
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/chinese-wok-ellis-bridge-cg-road-ahmedabad-636894",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "40831",
  "name": "Subway",
  "cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/4/4fe8d129-44fd-469e-9eda-a1416a6dffcd_40831.JPG",
  "locality": "Mithakali",
  "areaName": "Navrangpura",
  "costForTwo": "₹350 for two",
  "cuisines": [
  "Healthy Food",
  "Salads",
  "Snacks",
  "Desserts",
  "Beverages"
  ],
  "avgRating": 4.5,
  "parentId": "2",
  "avgRatingString": "4.5",
  "totalRatingsString": "1K+",
  "sla": {
  "deliveryTime": 30,
  "lastMileTravel": 1.8,
  "serviceability": "SERVICEABLE",
  "slaString": "25-30 mins",
  "lastMileTravelString": "1.8 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-14 23:59:00",
  "opened": true
  },
  "badges": {},
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {},
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "40% OFF",
  "subHeader": "UPTO ₹80"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "--"
  }
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/subway-mithakali-navrangpura-ahmedabad-40831",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "688452",
  "name": "La Pino'z Pizza",
  "cloudinaryImageId": "d20fdc8c86aa8bd0638f47dd013d46f9",
  "locality": "Capstone Kalgi Cross Road",
  "areaName": "Ellis Bridge",
  "costForTwo": "₹400 for two",
  "cuisines": [
  "Pizzas",
  "Pastas",
  "Italian",
  "Desserts",
  "Beverages"
  ],
  "avgRating": 4.5,
  "parentId": "4961",
  "avgRatingString": "4.5",
  "totalRatingsString": "500+",
  "sla": {
  "deliveryTime": 17,
  "lastMileTravel": 1.2,
  "serviceability": "SERVICEABLE",
  "slaString": "15-20 mins",
  "lastMileTravelString": "1.2 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-15 02:00:00",
  "opened": true
  },
  "badges": {
  "imageBadges": [
  {
  "imageId": "Rxawards/_CATEGORY-Pizza.png",
  "description": "Delivery!"
  }
  ]
  },
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {
  "badgeObject": [
  {
  "attributes": {
  "description": "Delivery!",
  "imageId": "Rxawards/_CATEGORY-Pizza.png"
  }
  }
  ]
  },
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "50% OFF",
  "subHeader": "UPTO ₹100"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "4.4",
  "ratingCount": "5K+"
  },
  "source": "GOOGLE",
  "sourceIconImageId": "v1704440323/google_ratings/rating_google_tag"
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/la-pinoz-pizza-capstone-kalgi-cross-road-ellis-bridge-ahmedabad-688452",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "81814",
  "name": "Burger King",
  "cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/4ee8bc77-ca9f-41bd-a0f3-511c70902b91_81814.JPG",
  "locality": "3rd Eye II,CG Road",
  "areaName": "Ellisbridge",
  "costForTwo": "₹350 for two",
  "cuisines": [
  "Burgers",
  "American",
  "Salads",
  "Beverages",
  "Chaat"
  ],
  "avgRating": 4.3,
  "parentId": "166",
  "avgRatingString": "4.3",
  "totalRatingsString": "10K+",
  "sla": {
  "deliveryTime": 21,
  "lastMileTravel": 1.7,
  "serviceability": "SERVICEABLE",
  "slaString": "20-25 mins",
  "lastMileTravelString": "1.7 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-15 05:00:00",
  "opened": true
  },
  "badges": {
  "imageBadges": [
  {
  "imageId": "Rxawards/_CATEGORY-Burger.png",
  "description": "Delivery!"
  }
  ]
  },
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {
  "badgeObject": [
  {
  "attributes": {
  "description": "Delivery!",
  "imageId": "Rxawards/_CATEGORY-Burger.png"
  }
  }
  ]
  },
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "60% OFF",
  "subHeader": "UPTO ₹120"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "4.0",
  "ratingCount": "1K+"
  },
  "source": "GOOGLE",
  "sourceIconImageId": "v1704440323/google_ratings/rating_google_tag"
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/burger-king-3rd-eye-ii-cg-road-ellisbridge-ahmedabad-81814",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "710033",
  "name": "The Belgian Waffle Co.",
  "cloudinaryImageId": "5116a385bac0548e06c33c08350fbf11",
  "locality": "Narayan Nagar Road",
  "areaName": "JOP PLAZA",
  "costForTwo": "₹200 for two",
  "cuisines": [
  "Waffle",
  "Desserts",
  "Ice Cream"
  ],
  "avgRating": 4.6,
  "veg": true,
  "parentId": "2233",
  "avgRatingString": "4.6",
  "totalRatingsString": "100+",
  "sla": {
  "deliveryTime": 30,
  "lastMileTravel": 3.7,
  "serviceability": "SERVICEABLE",
  "slaString": "30-35 mins",
  "lastMileTravelString": "3.7 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-15 00:00:00",
  "opened": true
  },
  "badges": {
  "imageBadges": [
  {
  "imageId": "v1695133679/badges/Pure_Veg111.png",
  "description": "pureveg"
  }
  ]
  },
  "isOpen": true,
  "aggregatedDiscountInfoV2": {},
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {
  "badgeObject": [
  {
  "attributes": {
  "description": "pureveg",
  "imageId": "v1695133679/badges/Pure_Veg111.png"
  }
  }
  ]
  },
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "--"
  }
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/the-belgian-waffle-co-narayan-nagar-road-jop-plaza-ahmedabad-710033",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "105268",
  "name": "UBQ By Barbeque Nation",
  "cloudinaryImageId": "nengejcwr1mhpjjgladx",
  "locality": "NEXUS AHMEDABAD ONE MALL",
  "areaName": "SARKARI VASAHAT ROAD",
  "costForTwo": "₹300 for two",
  "cuisines": [
  "Barbecue",
  "Biryani",
  "Kebabs",
  "Mughlai",
  "Desserts"
  ],
  "avgRating": 4.2,
  "parentId": "10804",
  "avgRatingString": "4.2",
  "totalRatingsString": "5K+",
  "sla": {
  "deliveryTime": 41,
  "lastMileTravel": 5,
  "serviceability": "SERVICEABLE",
  "slaString": "40-45 mins",
  "lastMileTravelString": "5.0 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-14 23:30:00",
  "opened": true
  },
  "badges": {},
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {},
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "50% OFF",
  "subHeader": "UPTO ₹100"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "--"
  }
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/ubq-by-barbeque-nation-nexus-one-mall-sarkari-vasahat-road-ahmedabad-105268",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "789441",
  "name": "Shreenath Farali Center",
  "cloudinaryImageId": "a8b1bddfe3c4d1cc4f361fc87558edf0",
  "locality": "Navrangpura",
  "areaName": "Law Garden, Navrangpura",
  "costForTwo": "₹200 for two",
  "cuisines": [
  "Snacks"
  ],
  "avgRating": 4.7,
  "veg": true,
  "parentId": "317759",
  "avgRatingString": "4.7",
  "totalRatingsString": "50+",
  "sla": {
  "deliveryTime": 16,
  "lastMileTravel": 2,
  "serviceability": "SERVICEABLE",
  "slaString": "15-20 mins",
  "lastMileTravelString": "2.0 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-14 21:45:00",
  "opened": true
  },
  "badges": {},
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {},
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "10% OFF",
  "subHeader": "ABOVE ₹1500",
  "discountTag": "FLAT DEAL"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "--"
  }
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/shreenath-farali-center-navrangpura-law-garden-navrangpura-ahmedabad-789441",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  },
  {
  "info": {
  "id": "52630",
  "name": "McDonald's",
  "cloudinaryImageId": "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/4a8bc67d-8fe4-44db-be5d-1477086cc52b_52630.JPG",
  "locality": "Ellis Bridge",
  "areaName": "Ashram Road",
  "costForTwo": "₹400 for two",
  "cuisines": [
  "Burgers",
  "Beverages",
  "Cafe",
  "Desserts"
  ],
  "avgRating": 4.5,
  "parentId": "630",
  "avgRatingString": "4.5",
  "totalRatingsString": "10K+",
  "sla": {
  "deliveryTime": 18,
  "lastMileTravel": 1.9,
  "serviceability": "SERVICEABLE",
  "slaString": "15-20 mins",
  "lastMileTravelString": "1.9 km",
  "iconType": "ICON_TYPE_EMPTY"
  },
  "availability": {
  "nextCloseTime": "2024-08-15 04:45:00",
  "opened": true
  },
  "badges": {
  "imageBadges": [
  {
  "imageId": "Rxawards/_CATEGORY-Burger.png",
  "description": "Delivery!"
  }
  ]
  },
  "isOpen": true,
  "type": "F",
  "badgesV2": {
  "entityBadges": {
  "imageBased": {
  "badgeObject": [
  {
  "attributes": {
  "description": "Delivery!",
  "imageId": "Rxawards/_CATEGORY-Burger.png"
  }
  }
  ]
  },
  "textBased": {},
  "textExtendedBadges": {}
  }
  },
  "aggregatedDiscountInfoV3": {
  "header": "30% OFF",
  "subHeader": "UPTO ₹75"
  },
  "orderabilityCommunication": {
  "title": {},
  "subTitle": {},
  "message": {},
  "customIcon": {}
  },
  "differentiatedUi": {
  "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
  "differentiatedUiMediaDetails": {
  "mediaType": "ADS_MEDIA_ENUM_IMAGE",
  "lottie": {},
  "video": {}
  }
  },
  "reviewsSummary": {},
  "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT",
  "restaurantOfferPresentationInfo": {},
  "externalRatings": {
  "aggregatedRating": {
  "rating": "4.2",
  "ratingCount": "5K+"
  },
  "source": "GOOGLE",
  "sourceIconImageId": "v1704440323/google_ratings/rating_google_tag"
  },
  "ratingsDisplayPreference": "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY"
  },
  "analytics": {
  "context": "seo-data-feb58a1a-7f13-4164-ab3a-a7ef59f2dbef"
  },
  "cta": {
  "link": "https://www.swiggy.com/restaurants/mcdonalds-ellis-bridge-ashram-road-ahmedabad-52630",
  "text": "RESTAURANT_MENU",
  "type": "WEBLINK"
  },
  "widgetId": "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo"
  }
  ]
