const data = [
    {
      id: "52630",
      name: "McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/4a8bc67d-8fe4-44db-be5d-1477086cc52b_52630.JPG",
      locality: "Ellis Bridge",
      areaName: "Ashram Road",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.5,
    },
    {
      id: "45454",
      name: "Subway",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/4/4fe8d129-44fd-469e-9eda-a1416a6dffcd_40831.JPG",
      locality: "Mithakali",
      areaName: "Navrangpura",
      costForTwo: "₹350 for two",
      cuisines: ["Healthy Food", "Salads", "Snacks", "Desserts", "Beverages"],
      avgRating: 4.5,
    },
    {id: "45455",
      name: "Shreenath Farali Center",
      cloudinaryImageId: "a8b1bddfe3c4d1cc4f361fc87558edf0",
      locality: "Navrangpura",
      areaName: "Law Garden, Navrangpura",
      costForTwo: "₹200 for two",
      cuisines: ["Snacks"],
      avgRating: 4.7,
    },
    {
      id: "45456",
      name: "UBQ By Barbeque Nation",
      cloudinaryImageId: "nengejcwr1mhpjjgladx",
      locality: "NEXUS AHMEDABAD ONE MALL",
      areaName: "SARKARI VASAHAT ROAD",
      costForTwo: "₹300 for two",
      cuisines: ["Barbecue", "Biryani", "Kebabs", "Mughlai", "Desserts"],
      avgRating: 4.2,
    },
    {
      id: "45457",
      name: "The Belgian Waffle Co.",
      cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
      locality: "Narayan Nagar Road",
      areaName: "JOP PLAZA",
      costForTwo: "₹200 for two",
      cuisines: ["Waffle", "Desserts", "Ice Cream"],
      avgRating: 4.6,
    },
    {
      id: "45458",
      name: "Burger King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/4ee8bc77-ca9f-41bd-a0f3-511c70902b91_81814.JPG",
      locality: "3rd Eye II,CG Road",
      areaName: "Ellisbridge",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American", "Salads", "Beverages", "Chaat"],
      avgRating: 4.3,
    },
    {
      id: "45459",
      name: "La Pino'z Pizza",
      cloudinaryImageId: "d20fdc8c86aa8bd0638f47dd013d46f9",
      locality: "Capstone Kalgi Cross Road",
      areaName: "Ellis Bridge",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRating: 4.5,
    },
    {
      id: "45460",
      name: "MAMA CHINESE",
      cuisines: "moglai,rice,noodles,veg.mogalai",
      avgRating: 3,
      cloudinaryImageId: "ye0cuamd3narriqobmrq",
    },
  ];

  export default data;